<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58581ba03ddd6',
	'fields' => array (
		array (
			'key' => 'field_58581c147c624',
			'label' => 'Suured-alad',
			'name' => 'suured-alad',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'58e28378232a5' => array (
					'key' => '58e28378232a5',
					'name' => 'galerii',
					'label' => 'Galerii',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58e28378232a6',
							'label' => 'pildid',
							'name' => 'pildid',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'insert' => 'append',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_58e28e9fda497',
							'label' => 'Klass',
							'name' => 'class',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58e28378232a7',
							'label' => 'ID',
							'name' => 'id-1',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5858264f8fbda' => array (
					'key' => '5858264f8fbda',
					'name' => 'sisu',
					'label' => 'Sisu',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5858265e8fbdb',
							'label' => 'text',
							'name' => 'text',
							'type' => 'qtranslate_wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '80',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_585abebfd7a7a',
							'label' => 'klass',
							'name' => 'klass',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '10',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_585ac1621e008',
							'label' => 'ID',
							'name' => 'id-2',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '10',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'585ac6a96a9bc' => array (
					'key' => '585ac6a96a9bc',
					'name' => 'full-image',
					'label' => 'Täispilt',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59351fcb58cd5',
							'label' => 'Täispildi seaded',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_585ac6d06a9c0',
							'label' => 'suur pilt',
							'name' => 'full-img',
							'type' => 'qtranslate_image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5932f1f647407',
							'label' => 'Sisutekst',
							'name' => 'sisutekst',
							'type' => 'qtranslate_wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_59351f9d58cd4',
							'label' => 'Rohkem valikuid',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_5932f21647408',
							'label' => 'Teksti joondus',
							'name' => 'joondus',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '15',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'lefttop' => 'üleval vasak',
								'righttop' => 'üleval parem',
								'leftbottom' => 'all vasakul',
								'rightbottom' => 'paremal all',
								'centercenter' => 'Keskel',
							),
							'default_value' => array (
								0 => 'center center',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5935205bf9550',
							'label' => 'Pildi joondus',
							'name' => 'pildi_joondus',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '15',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left top' => 'üleval vasak',
								'right top' => 'üleval parem',
								'left bottom' => 'all vasakul',
								'right bottom' => 'paremal all',
								'center center' => 'Keskel',
							),
							'default_value' => array (
								0 => 'center center',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_59352080f9551',
							'label' => 'Pildi kõrgus',
							'name' => 'pildi_korgus',
							'type' => 'text',
							'instructions' => 'Sisesta number 0 - 100-ni',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '15',
								'class' => '',
								'id' => '',
							),
							'default_value' => 45,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_585ac6aa6a9be',
							'label' => 'Klass',
							'name' => 'klass',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '15',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'59353d254f33e' => array (
					'key' => '59353d254f33e',
					'name' => 'tekstialad',
					'label' => 'Tekstialad',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_59353f3dae3ba',
							'label' => 'Tekstiala',
							'name' => 'tekstiala_repeater',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_59353f54ae3bb',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Lisa sisuala',
							'sub_fields' => array (
								array (
									'key' => 'field_59353f54ae3bb',
									'label' => 'Sisu',
									'name' => 'sisu_repeater',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'5947fe83625be' => array (
					'key' => '5947fe83625be',
					'name' => '23_ja_13',
					'label' => '2/3 ja 1/3 tekst',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_5947fe9e625bf',
							'label' => '2/3',
							'name' => 'kakskolmandikku',
							'type' => 'qtranslate_wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5947fec9625c0',
							'label' => '1/3',
							'name' => 'ukskolmandik',
							'type' => 'qtranslate_wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5947feff625c1' => array (
					'key' => '5947feff625c1',
					'name' => '13_13_13_tekst',
					'label' => '1/3 1/3 1/3 tekst',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59677e34a9eb5',
							'label' => 'Tekst',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_5947ff1f625c2',
							'label' => 'Vasakpoolne',
							'name' => 'vasakpoolne',
							'type' => 'qtranslate_wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5947ff4d625c3',
							'label' => 'Keskmine',
							'name' => 'keskmine',
							'type' => 'qtranslate_wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5947ff5f625c4',
							'label' => 'Parempoolne',
							'name' => 'parempoolne',
							'type' => 'qtranslate_wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_59677e7ea9eb6',
							'label' => 'Rohkem',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_59677eed5136c',
							'label' => 'Klass',
							'name' => 'class-1-3',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Lisa rida',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-section.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;

?>
